"""
RedHawk — Subdomain Enumeration Script
Performs DNS-based subdomain discovery using a small wordlist.
Usage: python subdomain_enum.py <domain>
"""

import sys
import json
import re
import socket


# Built-in mini wordlist for common subdomains
COMMON_SUBDOMAINS = [
    "www", "mail", "ftp", "admin", "blog", "api", "dev", "test", "stage",
    "app", "web", "webmail", "vpn", "remote", "portal", "support", "help",
    "shop", "store", "cdn", "static", "assets", "images", "img", "css",
    "js", "docs", "documentation", "wiki", "forum", "community", "chat",
    "status", "statuspage", "git", "github", "bitbucket", "jenkins",
    "jira", "confluence", "wiki", "sso", "login", "auth", "accounts",
    "owa", "exchange", "autodiscover", "lync", "skype", "teams",
    "calendar", "drive", "cloud", "dropbox", "box", "files", "transfer",
    "download", "uploads", "backup", "db", "database", "sql", "mysql",
    "redis", "mongo", "elastic", "es", "kibana", "grafana", "prometheus",
    "monitor", "monitoring", "logs", "analytics", "tracking", "pixel",
    "ads", "ad", "marketing", "newsletter", "email", "mta", "smtp",
    "imap", "pop3", "sip", "voip", "phone", "pbx", "asterisk",
    "ns1", "ns2", "ns3", "dns1", "dns2", "dns", "dnsserver",
    "mx", "mx1", "mx2", "smtp", "relay",
    "proxy", "squid", "gateway", "router", "switch", "firewall",
    "wifi", "wlan", "guest", "iot", "sensor", "camera", "cam",
    "host", "server", "node", "cluster", "k8s", "kubernetes",
    "docker", "registry", "npm", "maven", "pypi", "rubygems",
    "ci", "cd", "build", "deploy", "releases", "artifacts",
    "internal", "external", "partner", "vendor", "supplier",
    "intranet", "hr", "payroll", "invoice", "billing",
    "dashboard", "admin", "administrator", "root", "super",
    "phpmyadmin", "phpadmin", "adminer", "mysqladmin",
    "webmin", "cpanel", "whm", "plesk", "directadmin",
    "api", "v1", "v2", "v3", "rest", "graphql", "soap",
    "staging", "dev", "development", "qa", "testing",
    "prod", "production", "live", "release",
    "mobile", "m", "iphone", "android", "app",
    "lms", "learning", "moodle", "blackboard", "canvas",
    "recruit", "career", "jobs", "apply",
    "news", "press", "media", "events", "calendar",
    "survey", "polls", "feedback",
    "api-gateway", "gw", "edge", "lb", "loadbalancer",
    "waf", "ids", "ips", "security", "antivirus",
    "patches", "update", "updates", "software",
    "ticket", "tickets", "support", "desk", "zendesk",
    "status", "uptime", "health", "heartbeat",
    "stream", "video", "tv", "media", "player",
    "socket", "ws", "wss", "mqtt", "xmpp",
    "webhook", "hook", "callback",
    "config", "configuration", "settings",
    "s3", "storage", "bucket", "uploads",
    "new", "old", "beta", "alpha", "demo",
    "my", "your", "you", "the",
]

# Extended wordlist for common service-specific subdomains
SERVICE_SUBDOMAINS = [
    "acm", "acs", "adfs", "agile", "airwatch", "alerts",
    "anyconnect", "apigee", "appdynamics", "appsflyer",
    "atlassian", "audit", "auth0",
    "bastion", "bamboo", "biztalk",
    "bugzilla", "buildkite", "burst",
    "cas", "cassandra", "cctv", "centreon",
    "chef", "cipher", "circular", "cisco",
    "citrix", "cloudflare", "cobbler",
    "cognos", "collab", "compliance",
    "connect", "console", "consul",
    "content", "confluence", "control",
    "cordova", "corp", "cortex",
    "couchdb", "couchbase", "crashtest",
    "crucible", "crypt",
    "cyberark", "cybersource",
    "dabs", "daphne", "datadog",
    "datapower", "datastax", "datto",
    "dav", "dcos", "deep",
    "defect", "defender", "deployer",
    "desktop", "device", "devices",
    "devops", "digital", "discovery",
    "distelli", "dmz", "dnssec",
    "dockerhub", "docusign", "dovecot",
    "drupal", "dsm", "dump",
    "dynatrace", "dynamodb",
    "ebs", "echo", "ecommerce",
    "ediscovery", "egnyte", "ekb",
    "elasticbeanstalk", "elb", "elk",
    "emc", "ems", "endpoint",
    "enterprise", "epay", "epm",
    "esb", "eset", "etl",
    "euc", "eventbrite", "everbridge",
    "exchange", "express", "ext",
    "extranet", "f5", "facebook",
    "falcon", "fastly", "fax",
    "fcgi", "feeds", "filemaker",
    "fileshare", "firmware", "fishbowl",
    "flex", "flexnet", "flynn",
    "foreman", "forensic", "fortinet",
    "fortigate", "forum", "freeswitch",
    "ftp", "fusion",
    "gallery", "gcp", "gearman",
    "gerrit", "gitlab", "glpi",
    "gmail", "gmi", "gms",
    "gnats", "google", "googledrive",
    "gophish", "gov", "gps",
    "grafan", "grand", "greenplum",
    "group", "groupwise", "grp",
    "guest", "guide", "gunicorn",
    "hadoop", "harbor", "hardware",
    "hbase", "hdfs", "health",
    "heartbeat", "heroku", "hive",
    "hivemq", "hockeyapp", "honeypot",
    "horizon", "hp", "hpc",
    "hq", "hsqldb", "htpasswd",
    "http", "https", "hub",
    "hudson", "hunter", "hyperv",
    "iam", "ibm", "ice",
    "icinga", "identity", "idp",
    "iis", "im", "image",
    "imap", "ims", "in",
    "inbound", "index", "infoblox",
    "informix", "infra", "infrastructure",
    "inventory", "investor", "invoice",
    "iog", "iplanet", "ipsec",
    "ipv6", "irc", "iscsi",
    "iso", "isilon", "issue",
    "it", "itil", "ivr",
    "jabber", "jackrabbit", "jamf",
    "java", "jboss", "jdbc",
    "jeap", "jelly", "jenkins",
    "jetty", "jira", "jmeter",
    "jms", "job", "jobs",
    "jolokia", "journal", "jpo",
    "jrun", "json", "jsp",
    "jta", "jug", "jump",
    "jupyter", "jxplorer",
    "kafka", "kaltura", "kdc",
    "kendo", "kerio", "kerberos",
    "keybase", "keycloak", "keys",
    "kibana", "kiosk", "kit",
    "kms", "knox", "kofax",
    "kube", "kubectl", "kubernetes",
    "kvm", "lab", "labs",
    "lambda", "lampp", "lap",
    "laptop", "lastpass", "layar",
    "lb", "lcd", "ldap",
    "ldaps", "ldm", "lds",
    "learning", "lms", "load",
    "loader", "loadrunner", "locker",
    "locker", "login", "logistics",
    "logo", "logout", "logs",
    "logstash", "lookout", "lrs",
    "lucid", "lucene", "lumen",
    "lvs", "lync", "lyris",
    "m2m", "mac", "machine",
    "macos", "magic", "mail",
    "mailgun", "mailman", "main",
    "mainframe", "manage", "manager",
    "manila", "map", "mapi",
    "mapper", "marathon", "mariadb",
    "market", "marketing", "marketplace",
    "master", "maven", "maximo",
    "mblox", "mc", "mdaemon",
    "mdm", "media", "mediawiki",
    "meet", "mega", "memcached",
    "meraki", "merchant", "mercury",
    "meridian", "mesos", "messenger",
    "meta", "metrics", "mez",
    "mftp", "mgr", "micro",
    "microsite", "microsoft", "middleware",
    "migration", "mimecast", "minecraft",
    "mirror", "mirrors", "mis",
    "misc", "mobile", "mobility",
    "modsec", "modsecurity", "mogo",
    "mole", "mongodb", "monitor",
    "mono", "moodle", "moon",
    "motorola", "mount", "mouse",
    "moxa", "mozilla", "mq",
    "mqtt", "mrtg", "ms",
    "msc", "msce", "msd",
    "msde", "mse", "msi",
    "msk", "msmq", "mssql",
    "mstsc", "mt", "mta",
    "mule", "multi", "munin",
    "mural", "music", "musk",
    "mutillidae", "mvn", "my",
    "myadmin", "mybb", "myc",
    "mysql", "nagios", "name",
    "named", "nan", "nas",
    "nat", "native", "nav",
    "navision", "nb", "nba",
    "nbu", "nc", "nca",
    "ncc", "ncd", "ncp",
    "nd", "ndb", "ndc",
    "ndmp", "nds", "ne",
    "nebula", "nessus", "nest",
    "net", "netbackup", "netbeans",
    "netbios", "netflow", "netinfo",
    "netinst", "netlogon", "netmon",
    "netops", "netperf", "netscaler",
    "netsuite", "networking", "new",
    "newrelic", "news", "newsletter",
    "nfs", "nginx", "nh",
    "nfsen", "nfsen", "nfs",
    "ni", "nimbus", "ninja",
    "nintendo", "nis", "nism",
    "nms", "nn", "nnmi",
    "no", "node", "nodemcu",
    "nomad", "nop", "nor",
    "nosql", "notebook", "notes",
    "notification", "notify", "now",
    "np", "npd", "npm",
    "nps", "nr", "nrg",
    "ns", "nsa", "nsb",
    "nsc", "nsd", "nse",
    "nsf", "nsi", "nsl",
    "nsm", "nso", "nsp",
    "nsr", "nss", "nst",
    "nsx", "nt", "ntfs",
    "ntlm", "ntp", "ntpdate",
    "ntpdc", "ntpq", "ntsys",
    "nu", "nube", "nugget",
    "nunit", "nut", "nutanix",
    "nutcracker", "nv", "nvidia",
    "nvr", "nx", "nxlog",
    "nxos", "ny", "nyc",
    "nyx", "o", "oab",
    "oad", "oam", "oas",
    "oas", "oasis", "oauth",
    "ob", "obb", "ober",
    "obi", "obj", "object",
    "objectstore", "objs", "obl",
    "obs", "observer", "obsolete",
    "oc", "occ", "occi",
    "ocm", "ocp", "ocs",
    "oct", "octopus", "oculus",
    "odata", "odbc", "odds",
    "ode", "odf", "odi",
    "odl", "odm", "odo",
    "odp", "ods", "odt",
    "oe", "oem", "oer",
    "of", "ofb", "ofc",
    "ofdm", "ofs", "oft",
    "oftc", "og", "ogc",
    "ogh", "ogl", "ogo",
    "ogs", "ogv", "oh",
    "ohc", "ohd", "ohm",
    "ohs", "oi", "oia",
    "oid", "oim", "oir",
    "ois", "oit", "oj",
    "ojb", "ojdbc", "ojs",
    "ok", "okc", "okd",
    "okta", "ol", "olap",
    "olc", "old", "oldmail",
    "ole", "olh", "olio",
    "olm", "olp", "ols",
    "olsa", "olt", "olym",
    "om", "omc", "omd",
    "omi", "omni", "omnibus",
    "omr", "oms", "omv",
    "on", "oncall", "ond",
    "ondemand", "one", "oneadmin",
    "oneidentity", "onepage", "ones",
    "onesite", "onion", "online",
    "ons", "onsite", "ont",
    "ontap", "oo", "oob",
    "ooc", "oof", "oom",
    "oop", "oor", "oos",
    "oot", "oow", "op",
    "opc", "opcache", "open",
    "opencart", "openid", "opennebula",
    "openstack", "opentext", "openvpn",
    "openwebif", "opera", "operational",
    "operations", "operator", "oph",
    "opm", "opr", "ops",
    "opscenter", "opsview", "opt",
    "optim", "optimizer", "optimum",
    "option", "options", "opts",
    "opus", "or", "ora",
    "oracle", "orange", "orbit",
    "orc", "orch", "orchestrator",
    "order", "orders", "ordr",
    "ore", "oreilly", "org",
    "organ", "organic", "organization",
    "orgchart", "orgs", "orient",
    "orientdb", "origin", "origins",
    "orion", "orn", "orx",
    "os", "osb", "osc",
    "oscon", "osdc", "ose",
    "osfc", "osgi", "osh",
    "osimage", "osint", "osis",
    "osmc", "ossec", "ossim",
    "ost", "osticket", "osx",
    "ot", "ota", "otc",
    "otel", "oth", "other",
    "otp", "otrs", "ots",
    "ott", "otus", "ou",
    "ou812", "out", "outage",
    "outbound", "outcomes", "outdoor",
    "outfit", "outgoing", "outlet",
    "outline", "outlook", "outpost",
    "output", "outsource", "outsystems",
    "ouverture", "ov", "ovation",
    "oven", "over", "overland",
    "overlay", "overload", "override",
    "overview", "ovh", "ovirt",
    "ow", "owasp", "ower",
    "owl", "own", "owncloud",
    "owner", "ox", "oxford",
    "oxid", "oxygen", "oz",
    "ozone", "p", "p4",
    "p6", "p7m", "pa",
    "pab", "pace", "pacifica",
    "pack", "package", "packager",
    "packages", "packet", "packeth",
    "packetizer", "packing", "packs",
    "pad", "paddle", "pads",
    "paf", "page", "pagekit",
    "pager", "pagerduty", "pages",
    "pagseguro", "paid", "paidsupport",
    "pain", "paint", "pair",
    "paj", "pak", "pal",
    "pale", "palo", "paloalto",
    "pam", "pamela", "pan",
    "panacea", "panasonic", "pandora",
    "panel", "panic", "panorama",
    "pantheon", "panther", "pap",
    "paper", "papercut", "paperless",
    "paperport", "papers", "papyrus",
    "par", "parabola", "parachute",
    "paradigm", "paradise", "paragon",
    "parallels", "parameter", "paramount",
    "parasite", "parature", "parcel",
    "parent", "parental", "parents",
    "paris", "park", "parked",
    "parking", "parks", "parrot",
    "parse", "parser", "parsers",
    "part", "particle", "parties",
    "partition", "partly", "partner",
    "partners", "parts", "party",
    "pass", "passage", "passbolt",
    "passed", "passenger", "passport",
    "password", "passwords", "paste",
    "pastebin", "paster", "pastie",
    "pat", "patch", "patches",
    "patching", "path", "pathology",
    "paths", "patient", "patio",
    "pato", "patreon", "pats",
    "pattern", "patterns", "paul",
    "pause", "pav", "pave",
    "pavement", "pavilion", "paw",
    "pawn", "pay", "payday",
    "payflow", "payjunction", "payload",
    "payment", "payments", "payoneer",
    "paypal", "paypal", "payper",
    "payroll", "pays", "payscale",
    "payslip", "payson", "paytm",
    "pbc", "pbm", "pbr",
    "pbx", "pc", "pcb",
    "pcc", "pcd", "pce",
    "pci", "pcloud", "pcm",
    "pco", "pcs", "pct",
    "pda", "pdc", "pdd",
    "pdf", "pdns", "pdp",
    "pds", "pdt", "pe",
    "peace", "peak", "peanut",
    "pear", "pearl", "pebble",
    "pec", "pech", "pecos",
    "ped", "pedestal", "pedro",
    "peek", "peel", "peer",
    "peering", "peers", "peg",
    "pegass", "pega", "pegasus",
    "pel", "pelle", "pelm",
    "pem", "pen", "penal",
    "pencil", "pend", "pending",
    "peng", "penny", "pension",
    "pent", "pentaho", "pentest",
    "pentesting", "pentoo", "people",
    "peoplesoft", "pep", "pepper",
    "per", "perceptive", "percona",
    "percussion", "percy", "perdition",
    "perf", "perforce", "perfsonar",
    "perg", "perimeter", "perl",
    "perl5", "perlb", "perlbin",
    "perldoc", "perlman", "perlmonks",
    "perls", "perltidy", "perm",
    "permanent", "permission", "permissions",
    "permit", "permit", "pers",
    "persistence", "persistent", "person",
    "personal", "personas", "personnel",
    "perspect", "perspectives", "perth",
    "pert", "peru", "pervasive",
    "pes", "pest", "pet",
    "peta", "petabytes", "petition",
    "petr", "petri", "petroleum",
    "pets", "petscan", "petsmart",
    "pew", "pewpew", "pex",
    "pexels", "pexeso", "pf",
    "pfc", "pfd", "pfe",
    "pfs", "pfsense", "pg",
    "pgadmin", "pgb", "pgc",
    "pgd", "pge", "pgg",
    "pgh", "pgi", "pgii",
    "pgina", "pgm", "pgmb",
    "pgp", "pgpool", "pgr",
    "pgs", "pgsql", "pgt",
    "pgx", "ph", "phantom",
    "phantomjs", "pharmacy", "phase",
    "phases", "phat", "phb",
    "phd", "phe", "phenom",
    "phenotype", "phex", "phi",
    "phil", "philadelphia", "philips",
    "phillips", "phish", "phishing",
    "phlo", "phobos", "phoenix",
    "phone", "phones", "phonetic",
    "phong", "phorum", "phosphor",
    "photo", "photobucket", "photograph",
    "photography", "photos", "phrase",
    "phreak", "phrozen", "phtml",
    "phusion", "phx", "phy",
    "phylo", "phys", "physical",
    "physics", "physio", "phyt",
    "pi", "pian", "piano",
    "pic", "pica", "picasso",
    "piccolo", "pich", "pick",
    "picker", "pickle", "pickup",
    "picnic", "pico", "picplz",
    "pics", "pict", "picture",
    "pictures", "pide", "pie",
    "piece", "pieces", "pied",
    "pier", "pierre", "piet",
    "pig", "pigeon", "piggy",
    "pihole", "pik", "pike",
    "pile", "piles", "pilgrim",
    "pill", "pillar", "pillow",
    "pilot", "pilots", "pim",
    "pimple", "pin", "pinax",
    "pinboard", "pinc", "pincer",
    "pinch", "pine", "pineapple",
    "ping", "pingdom", "pinhole",
    "pinion", "pink", "pinky",
    "pinned", "pino", "pins",
    "pint", "pinto", "pinw",
    "pioneer", "pionen", "pios",
    "pip", "pipe", "pipeline",
    "pipelines", "piper", "pipet",
    "piping", "pips", "piqu",
    "pir", "piranha", "pirate",
    "pirated", "pirates", "piro",
    "pirx", "pis", "pisa",
    "pisc", "piserver", "piss",
    "pissoff", "pist", "pistol",
    "pit", "pitch", "pitcher",
    "pith", "piton", "pitt",
    "pittsburgh", "pity", "pivot",
    "pivotal", "pixel", "pixels",
    "pixi", "pixie", "pixx",
    "pizza", "pizzaria", "pizzeria",
    "pj", "pja", "pjb",
    "pjc", "pje", "pjh",
    "pjm", "pjp", "pjs",
    "pjw", "pk", "pkc",
    "pki", "pkm", "pkn",
    "pkr", "pks", "pkt",
    "pktgen", "pktstat", "pku",
    "pl", "place", "placebo",
    "placeholder", "places", "placet",
    "placid", "plag", "plague",
    "plain", "plains", "plaint",
    "plan", "plane", "planet",
    "planetlab", "planner", "plans",
    "plant", "plantain", "plantao",
    "planti", "plants", "plany",
    "plaque", "plash", "plasm",
    "plasma", "plast", "plastic",
    "plate", "plateau", "plated",
    "platen", "plates", "platform",
    "platformsh", "platinum", "plato",
    "platon", "platoo", "platy",
    "play", "playa", "playback",
    "playbook", "playbox", "player",
    "playground", "playlist", "plays",
    "playsms", "playstation", "playwright",
    "plaza", "ple", "plead",
    "please", "pleasure", "pledge",
    "plek", "plenty", "plex",
    "plexus", "pli", "plib",
    "plie", "plight", "plink",
    "plinth", "plist", "plm",
    "plone", "plot", "plotter",
    "plough", "plov", "plow",
    "plowshare", "ploy", "plr",
    "pls", "plug", "plugin",
    "plugins", "plugo", "plumb",
    "plumber", "plumbing", "plume",
    "plumer", "plumtree", "plunder",
    "plunk", "plup", "plura",
    "plural", "pluralsight", "plus",
    "pluto", "pluton", "plutus",
    "ply", "plymouth", "pm",
    "pma", "pmail", "pmc",
    "pmd", "pme", "pmg",
    "pmi", "pml", "pmma",
    "pmm", "pmn", "pmo",
    "pmr", "pms", "pmt",
    "pmu", "pmw", "pn",
    "pn532", "pna", "pnb",
    "pnc", "pnd", "pne",
    "pnet", "pnfs", "png",
    "pni", "pnid", "pnik",
    "pnm", "pnp", "pns",
    "pnt", "pnu", "pnw",
    "po", "poa", "poam",
    "pob", "pobox", "poc",
    "pock", "pocket", "poco",
    "pod", "podcast", "podcasts",
    "podium", "pods", "poe",
    "poem", "poems", "poet",
    "poetry", "pogo", "point",
    "pointer", "pointers", "points",
    "poise", "poison", "poke",
    "poker", "pol", "polar",
    "polaris", "pole", "police",
    "policy", "polish", "polito",
    "politron", "polity", "polka",
    "poll", "polling", "polls",
    "pollux", "polo", "polter",
    "poly", "polycom", "polygon",
    "polygraph", "polymer", "polytechnic",
    "pom", "pomade", "pomegranate",
    "pomp", "pompe", "pompeii",
    "pompidou", "pon", "poncho",
    "pond", "ponies", "pont",
    "pontoon", "pony", "ponytail",
    "pool", "pooler", "pools",
    "poor", "poorly", "pop",
    "pop3", "popcorn", "pope",
    "popeye", "popo", "popp",
    "popper", "poppet", "poppy",
    "pops", "popular", "populate",
    "population", "popup", "pore",
    "pork", "porkbun", "porkchop",
    "porn", "porno", "pornolab",
    "port", "porta", "portable",
    "portal", "portals", "porter",
    "portfolio", "porth", "portico",
    "portier", "portion", "portlet",
    "porto", "portrait", "ports",
    "portsmouth", "portugal", "portworx",
    "pos", "pose", "poseidon",
    "posh", "posit", "position",
    "positive", "posse", "possess",
    "possum", "post", "postal",
    "postback", "postbox", "postcard",
    "poste", "poster", "postfix",
    "postgis", "postgres", "postgresql",
    "postmark", "postmaster", "postnuke",
    "postoffice", "posts", "postscript",
    "posture", "postwick", "pot",
    "potato", "potatoes", "potbox",
    "potd", "pote", "potent",
    "potential", "poth", "potion",
    "potluck", "potoo", "potoroo",
    "pots", "pott", "potter",
    "pottery", "pouch", "pouf",
    "poul", "pounce", "pound",
    "pour", "pous", "pout",
    "poutine", "pov", "poverty",
    "pow", "powder", "powell",
    "power", "powered", "powerful",
    "powerhouse", "poweroff", "poweron",
    "powers", "powersave", "powershell",
    "powerup", "pp", "ppb",
    "ppc", "ppd", "ppf",
    "ppg", "pph", "ppi",
    "ppl", "ppm", "ppp",
    "pppd", "pppoe", "pppstats",
    "ppr", "pps", "ppt",
    "pptp", "ppw", "pq",
    "pqa", "pqc", "pqd",
    "pql", "pqq", "pqt",
    "pr", "prag", "prague",
    "praise", "praj", "prak",
    "pran", "prank", "prankster",
    "prav", "pray", "prayer",
    "prd", "pre", "preach",
    "preamp", "prec", "precast",
    "precedent", "precious", "precip",
    "precision", "precon", "preconf",
    "pred", "predator", "predefined",
    "prediction", "predictions", "prefab",
    "prefect", "prefecture", "prefer",
    "preference", "preferences", "prefix",
    "prefs", "preh", "prehist",
    "preinst", "prelander", "prelink",
    "preload", "preloader", "prem",
    "premier", "premise", "premises",
    "premium", "pren", "prensa",
    "prep", "prepaid", "preparation",
    "prepare", "prepared", "preparser",
    "prepcs", "prepper", "prepress",
    "preprod", "prer", "prereq",
    "prereqs", "pres", "presale",
    "presales", "presc", "prescott",
    "prescr", "prese", "presence",
    "present", "presentation", "presenter",
    "presenters", "presently", "presents",
    "preserv", "preserve", "preset",
    "presets", "presi", "president",
    "presidio", "preso", "press",
    "pressa", "presscenter", "pressed",
    "presses", "presskit", "pressroom",
    "pressrun", "pressure", "prest",
    "presta", "prestadb", "prestashop",
    "presto", "presumably", "presume",
    "preteen", "pretend", "pretender",
    "pretext", "pretoria", "pretty",
    "pretzel", "prev", "prevail",
    "prevent", "prevention", "preview",
    "previews", "prevue", "prew",
    "preweb", "prez", "prezzi",
    "prf", "prg", "pri",
    "price", "priced", "priceless",
    "prices", "pricey", "pricin",
    "pricing", "prid", "pride",
    "priest", "prig", "prim",
    "prima", "primary", "primate",
    "prime", "primer", "primers",
    "primeur", "primitive", "primo",
    "primrose", "prince", "princess",
    "princeton", "princip", "principal",
    "principle", "principles", "print",
    "printable", "printers", "printing",
    "printr", "prints", "prior",
    "priority", "prism", "prison",
    "prisoner", "pristine", "priv",
    "privacy", "private", "privilege",
    "privileged", "privileges", "privkey",
    "prive", "privet", "privi",
    "privia", "privilege", "privity",
    "prix", "prize", "prizes",
    "prj", "prk", "prm",
    "prn", "pro", "proactive",
    "prob", "probable", "probably",
    "probate", "probe", "probeer",
    "probes", "probity", "problem",
    "problems", "proc", "procard",
    "proceed", "proceedings", "process",
    "processor", "processors", "proch",
    "proclaim", "procmail", "procomm",
    "procreate", "procs", "procurve",
    "procyon", "prod", "prodigy",
    "prodmgmt", "prodo", "prodr",
    "prods", "prodsrv", "product",
    "production", "productions", "productive",
    "productivity", "products", "proem",
    "proeng", "prof", "profanity",
    "profect", "profess", "profession",
    "professional", "professor", "proffer",
    "profile", "profiles", "profit",
    "profits", "progen", "progman",
    "progn", "program", "programmable",
    "programma", "programmer", "programmers",
    "programming", "programs", "progress",
    "progresql", "proh", "prohibit",
    "project", "projector", "projectors",
    "projects", "projman", "projs",
    "prokop", "prol", "prolan",
    "proliant", "prolific", "prolog",
    "prologs", "prom", "prometheus",
    "promise", "promises", "promo",
    "promote", "promotion", "promotions",
    "prompt", "prompts", "promul",
    "pron", "prone", "pronet",
    "pronounce", "pronter", "proo",
    "proof", "proofpoint", "prop",
    "propane", "propel", "propeller",
    "proper", "property", "proph",
    "prophase", "prophet", "propolis",
    "proport", "proposal", "proposals",
    "propose", "proposed", "proposition",
    "propre", "props", "propy",
    "pror", "pros", "prosc",
    "prose", "prosec", "prosody",
    "prospect", "prospects", "prosper",
    "prost", "prostate", "prostor",
    "prosze", "prot", "protect",
    "protected", "protecting", "protection",
    "protective", "protector", "protectors",
    "protege", "protei", "protein",
    "protel", "proteon", "proteus",
    "proth", "prothe", "proti",
    "protobuf", "protocol", "protocols",
    "protom", "proton", "protools",
    "prototype", "prototypes", "protoz",
    "protract", "protrp", "prott",
    "prou", "proud", "proust",
    "prova", "proval", "prove",
    "proved", "proven", "provent",
    "proverb", "proverbs", "provid",
    "provide", "provided", "provider",
    "providers", "provides", "province",
    "provision", "provisions", "provisor",
    "provo", "provoc", "provost",
    "prow", "prowess", "prowl",
    "prowler", "prox", "proxies",
    "proxim", "proximate", "proximo",
    "proxy", "proyect", "proza",
    "prozac", "prozess", "prp",
    "prq", "prr", "prs",
    "prt", "prtg", "prtn",
    "prts", "pru", "prud",
    "prudential", "prune", "pruning",
    "prus", "prussian", "pry",
    "prz", "ps", "psa",
    "psad", "psalm", "psalms",
    "psaux", "psb", "psc",
    "psd", "pse", "psf",
    "psg", "psh", "psi",
    "psij", "psion", "psionic",
    "pskov", "psl", "psm",
    "psn", "pso", "psp",
    "psql", "psr", "pss",
    "pst", "pstg", "psu",
    "pswitch", "psx", "psy",
    "psych", "psychiatry", "psychic",
    "psycho", "psychology", "psycho",
    "psyco", "psync", "psyop",
    "pt", "pta", "ptc",
    "ptd", "pte", "ptf",
    "pthc", "pti", "ptm",
    "ptn", "pto", "ptp",
    "ptr", "pts", "ptt",
    "ptu", "ptv", "pty",
    "pu", "pub", "puberty",
    "pubg", "public", "publica",
    "publican", "publications", "publicidad",
    "publicity", "publickey", "publish",
    "publisher", "publishers", "publishing",
    "pubs", "puc", "puck",
    "pudd", "puddle", "puddly",
    "puer", "puerco", "puff",
    "puffer", "puffy", "pug",
    "pugil", "puglia", "pugwash",
    "pui", "puk", "pukar",
    "puke", "pul", "pula",
    "pular", "pulc", "pull",
    "puller", "pulley", "pulling",
    "pullman", "pullover", "pulls",
    "pulp", "pulpit", "puls",
    "pulse", "pulsed", "pulser",
    "puma", "pummel", "pump",
    "pumper", "pumping", "pumpkin",
    "pumps", "pun", "punbb",
    "punch", "puncher", "punct",
    "puncture", "pundit", "pung",
    "punish", "punk", "punks",
    "punt", "punter", "punto",
    "puola", "pup", "pupil",
    "pupils", "puppet", "puppeteer",
    "puppets", "puppy", "pur",
    "pura", "purcell", "purch",
    "purchase", "purchased", "purchases",
    "purchasing", "pure", "purebred",
    "pureftpd", "purely", "purg",
    "purge", "purged", "purging",
    "puri", "purif", "purify",
    "purina", "purism", "puritan",
    "puritanic", "purity", "purle",
    "purp", "purple", "purport",
    "purpose", "purposes", "purr",
    "purse", "pursuant", "pursue",
    "pursuer", "pursuit", "purus",
    "purview", "pus", "pusc",
    "push", "pushbutton", "pusher",
    "pushover", "pushpin", "pussy",
    "pussycat", "put", "puta",
    "putain", "putas", "putdown",
    "putlocker", "puto", "putr",
    "putrefy", "puts", "putsch",
    "putt", "putter", "putty",
    "puzzle", "puzzled", "puzzles",
    "puzzling", "pv", "pva",
    "pvc", "pve", "pvfs",
    "pvh", "pvm", "pvp",
    "pvs", "pvt", "pw",
    "pwa", "pwb", "pwc",
    "pwd", "pwdgen", "pwdhash",
    "pwdmgr", "pwdump", "pwe",
    "pwf", "pwg", "pwh",
    "pwi", "pwmail", "pwn",
    "pwnd", "pwned", "pwner",
    "pwnies", "pwns", "pwr",
    "pwrstat", "pws", "pwt",
    "pwx", "px", "pxe",
    "pxeboot", "pxegrub", "pxelinux",
    "pxes", "pxgrid", "pxp",
    "pxproxy", "pxy", "py",
    "py3", "pya", "pyar",
    "pyc", "pycheck", "pyconf",
    "pycrypt", "pyd", "pydio",
    "pyel", "pyfib", "pyfl",
    "pygame", "pygmy", "pygotham",
    "pygr", "pygrep", "pyha",
    "pyin", "pyjs", "pyl",
    "pylab", "pylabs", "pylint",
    "pyload", "pylon", "pylons",
    "pym", "pymail", "pymc",
    "pymol", "pymp", "pymqi",
    "pyn", "pynlp", "pyo",
    "pyodbc", "pyon", "pyopen",
    "pyorg", "pyp", "pypal",
    "pypandoc", "pypanel", "pyparty",
    "pype", "pyped", "pypi",
    "pypi", "pypo", "pyproj",
    "pyramid", "pyro", "pyrom",
    "pyrr", "pys", "pys60",
    "pysa", "pysap", "pyscard",
    "pyscopg", "pysft", "pyside",
    "pysol", "pyspec", "pyspi",
    "pyspider", "pyss", "pyst",
    "pyston", "pysw", "pysync",
    "pyt", "pytables", "pytags",
    "pythag", "pythia", "python",
    "python3", "pythonia", "pythonic",
    "pytils", "pytom", "pytube",
    "pyua", "pyui", "pyur",
    "pyv", "pyvis", "pyvm",
    "pyvox", "pyvows", "pyw",
    "pyweb", "pywf", "pywhy",
    "pywik", "pywikibot", "pywin",
    "pywinauto", "pywinrm", "pyx",
    "pyxie", "pyxis", "pyy",
    "pyzor", "pyzz", "pz",
    "pza", "pzb", "pzc",
    "pzd", "pzf", "pzh",
    "pzi", "pzk", "pzl",
    "pzm", "pzn", "pzp",
    "pzr", "pzs", "pzt",
    "pzu", "pzv", "pzw",
    "pzz", "q", "qa",
    "qaa", "qab", "qac",
    "qad", "qae", "qaf",
    "qag", "qah", "qai",
    "qaj", "qak", "qal",
    "qam", "qan", "qao",
    "qap", "qaq", "qar",
    "qas", "qat", "qau",
    "qav", "qaw", "qax",
    "qay", "qaz", "qb",
    "qba", "qbb", "qbc",
    "qbd", "qbe", "qbf",
    "qbg", "qbh", "qbi",
    "qbj", "qbk", "qbl",
    "qbm", "qbn", "qbo",
    "qbp", "qbq", "qbr",
    "qbs", "qbt", "qbu",
    "qbv", "qbw", "qbx",
    "qby", "qbz", "qc",
    "qca", "qcb", "qcc",
    "qcd", "qce", "qcf",
    "qcg", "qch", "qci",
    "qcj", "qck", "qcl",
    "qcm", "qcn", "qco",
    "qcp", "qcq", "qcr",
    "qcs", "qct", "qcu",
    "qcv", "qcw", "qcx",
    "qcy", "qcz", "qd",
    "qda", "qdb", "qdc",
    "qdd", "qde", "qdf",
    "qdg", "qdh", "qdi",
    "qdj", "qdk", "qdl",
    "qdm", "qdn", "qdo",
    "qdp", "qdq", "qdr",
    "qds", "qdt", "qdu",
    "qdv", "qdw", "qdx",
    "qdy", "qdz", "qe",
    "qea", "qeb", "qec",
    "qed", "qee", "qef",
    "qeg", "qeh", "qei",
    "qej", "qek", "qel",
    "qem", "qen", "qeo",
    "qep", "qeq", "qer",
    "qes", "qet", "qeu",
    "qev", "qew", "qex",
    "qey", "qez", "qf",
    "qfa", "qfb", "qfc",
    "qfd", "qfe", "qff",
    "qfg", "qfh", "qfi",
    "qfj", "qfk", "qfl",
    "qfm", "qfn", "qfo",
    "qfp", "qfq", "qfr",
    "qfs", "qft", "qfu",
    "qfv", "qfw", "qfx",
    "qfy", "qfz", "qg",
    "qga", "qgb", "qgc",
    "qgd", "qge", "qgf",
    "qgg", "qgh", "qgi",
    "qgj", "qgk", "qgl",
    "qgm", "qgn", "qgo",
    "qgp", "qgq", "qgr",
    "qgs", "qgt", "qgu",
    "qgv", "qgw", "qgx",
    "qgy", "qgz", "qh",
    "qha", "qhb", "qhc",
    "qhd", "qhe", "qhf",
    "qhg", "qhh", "qhi",
    "qhj", "qhk", "qhl",
    "qhm", "qhn", "qho",
    "qhp", "qhq", "qhr",
    "qhs", "qht", "qhu",
    "qhv", "qhw", "qhx",
    "qhy", "qhz", "qi",
    "qia", "qib", "qic",
    "qid", "qie", "qif",
    "qig", "qih", "qii",
    "qij", "qik", "qil",
    "qim", "qin", "qio",
    "qip", "qiq", "qir",
    "qis", "qit", "qiu",
    "qiv", "qiw", "qix",
    "qiy", "qiz", "qj",
    "qja", "qjb", "qjc",
    "qjd", "qje", "qjf",
    "qjg", "qjh", "qji",
    "qjj", "qjk", "qjl",
    "qjm", "qjn", "qjo",
    "qjp", "qjq", "qjr",
    "qjs", "qjt", "qju",
    "qjv", "qjw", "qjx",
    "qjy", "qjz", "qk",
    "qka", "qkb", "qkc",
    "qkd", "qke", "qkf",
    "qkg", "qkh", "qki",
    "qkj", "qkk", "qkl",
    "qkm", "qkn", "qko",
    "qkp", "qkq", "qkr",
    "qks", "qkt", "qku",
    "qkv", "qkw", "qkx",
    "qky", "qkz", "ql",
    "qla", "qlb", "qlc",
    "qld", "qle", "qlf",
    "qlg", "qlh", "qli",
    "qlj", "qlk", "qll",
    "qlm", "qln", "qlo",
    "qlp", "qlq", "qlr",
    "qls", "qlt", "qlu",
    "qlv", "qlw", "qlx",
    "qly", "qlz", "qm",
    "qma", "qmb", "qmc",
    "qmd", "qme", "qmf",
    "qmg", "qmh", "qmi",
    "qmj", "qmk", "qml",
    "qmm", "qmn", "qmo",
    "qmp", "qmq", "qmr",
    "qms", "qmt", "qmu",
    "qmv", "qmw", "qmx",
    "qmy", "qmz", "qn",
    "qna", "qnb", "qnc",
    "qnd", "qne", "qnf",
    "qng", "qnh", "qni",
    "qnj", "qnk", "qnl",
    "qnm", "qnn", "qno",
    "qnp", "qnq", "qnr",
    "qns", "qnt", "qnu",
    "qnv", "qnw", "qnx",
    "qny", "qnz", "qo",
    "qoa", "qob", "qoc",
    "qod", "qoe", "qof",
    "qog", "qoh", "qoi",
    "qoj", "qok", "qol",
    "qom", "qon", "qoo",
    "qop", "qoq", "qor",
    "qos", "qot", "qou",
    "qov", "qow", "qox",
    "qoy", "qoz", "qp",
    "qpa", "qpb", "qpc",
    "qpd", "qpe", "qpf",
    "qpg", "qph", "qpi",
    "qpj", "qpk", "qpl",
    "qpm", "qpn", "qpo",
    "qpp", "qpq", "qpr",
    "qps", "qpt", "qpu",
    "qpv", "qpw", "qpx",
    "qpy", "qpz", "qq",
    "qqa", "qqb", "qqc",
    "qqd", "qqe", "qqf",
    "qqg", "qqh", "qqi",
    "qqj", "qqk", "qql",
    "qqm", "qqn", "qqo",
    "qqp", "qqq", "qqr",
    "qqs", "qqt", "qqu",
    "qqv", "qqw", "qqx",
    "qqy", "qqz", "qr",
]


def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No domain provided. Usage: subdomain_enum.py <domain>"}))
        sys.exit(1)

    domain = sys.argv[1].strip().lower()
    domain = re.sub(r'^https?://', '', domain)
    domain = domain.split('/')[0]
    domain = domain.split('?')[0]

    found = []
    wordlist = COMMON_SUBDOMAINS + SERVICE_SUBDOMAINS
    # Deduplicate while preserving order
    seen = set()
    unique_words = []
    for w in wordlist:
        if w not in seen:
            seen.add(w)
            unique_words.append(w)

    total = len(unique_words)
    found_count = 0

    for i, sub in enumerate(unique_words):
        fqdn = f"{sub}.{domain}"
        try:
            ip = socket.gethostbyname(fqdn)
            found.append({"subdomain": fqdn, "ip": ip})
            found_count += 1
        except socket.gaierror:
            pass
        except Exception:
            pass

    # Sort found subdomains
    found.sort(key=lambda x: x["subdomain"])

    result = {
        "domain": domain,
        "subdomains": [f["subdomain"] for f in found],
        "details": found,
        "count": found_count,
        "totalChecked": total,
    }

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
